import dotenv from 'dotenv';
import pool from '../src/config/database';

dotenv.config();

interface SeedExercise {
  name: string;
  primary_muscle_group?: string;
  secondary_muscle_groups?: string[];
  movement_pattern?: string;
  equipment?: string;
  category?: string;
  default_sets?: number;
  default_reps?: string;
  default_load?: string;
  default_rest_seconds?: number;
  default_tempo?: string;
  notes?: string;
}

// NOTE: This is a curated seed list focused on your available equipment:
// dumbbells, rack, barbell, bench, nordic curler, ski erg, sled, bands, bike erg, treadmill, box.
// It covers ~60+ of the most useful patterns; you can extend this list over time.
const EXERCISES: SeedExercise[] = [
  // Barbell lower body (rack + barbell)
  {
    name: 'Barbell Back Squat',
    primary_muscle_group: 'Quads',
    secondary_muscle_groups: ['Glutes'],
    movement_pattern: 'Squat',
    equipment: 'Barbell/Rack',
    category: 'Strength',
    default_sets: 3,
    default_reps: '5',
    default_load: 'Heavy (RIR 2)',
    default_rest_seconds: 180,
  },
  {
    name: 'Barbell Front Squat',
    primary_muscle_group: 'Quads',
    secondary_muscle_groups: ['Glutes'],
    movement_pattern: 'Squat',
    equipment: 'Barbell/Rack',
    category: 'Strength',
    default_sets: 3,
    default_reps: '5–8',
    default_load: 'Moderate-Heavy',
    default_rest_seconds: 150,
  },
  {
    name: 'Barbell Romanian Deadlift',
    primary_muscle_group: 'Hamstrings',
    secondary_muscle_groups: ['Glutes', 'Lower Back'],
    movement_pattern: 'Hinge',
    equipment: 'Barbell/Rack',
    category: 'Strength',
    default_sets: 3,
    default_reps: '6–8',
    default_load: 'Moderate-Heavy',
    default_rest_seconds: 150,
  },
  {
    name: 'Conventional Deadlift',
    primary_muscle_group: 'Posterior Chain',
    secondary_muscle_groups: ['Glutes', 'Hamstrings', 'Back'],
    movement_pattern: 'Hinge',
    equipment: 'Barbell/Rack',
    category: 'Strength',
    default_sets: 3,
    default_reps: '3–5',
    default_load: 'Heavy',
    default_rest_seconds: 180,
  },
  {
    name: 'Sumo Deadlift',
    primary_muscle_group: 'Posterior Chain',
    secondary_muscle_groups: ['Glutes', 'Hamstrings'],
    movement_pattern: 'Hinge',
    equipment: 'Barbell/Rack',
    category: 'Strength',
    default_sets: 3,
    default_reps: '3–5',
    default_load: 'Heavy',
    default_rest_seconds: 180,
  },
  {
    name: 'Barbell Split Squat',
    primary_muscle_group: 'Quads',
    secondary_muscle_groups: ['Glutes'],
    movement_pattern: 'Lunge',
    equipment: 'Barbell/Rack',
    category: 'Hypertrophy',
    default_sets: 3,
    default_reps: '6–10/leg',
    default_load: 'Moderate',
    default_rest_seconds: 120,
  },
  {
    name: 'Barbell Walking Lunge',
    primary_muscle_group: 'Quads',
    secondary_muscle_groups: ['Glutes', 'Hamstrings'],
    movement_pattern: 'Lunge',
    equipment: 'Barbell/Rack',
    category: 'Hypertrophy',
    default_sets: 3,
    default_reps: '8–12/leg',
    default_load: 'Moderate',
    default_rest_seconds: 120,
  },

  // Barbell upper body
  {
    name: 'Barbell Bench Press',
    primary_muscle_group: 'Chest',
    secondary_muscle_groups: ['Triceps', 'Shoulders'],
    movement_pattern: 'Horizontal Push',
    equipment: 'Barbell/Bench',
    category: 'Strength',
    default_sets: 3,
    default_reps: '5–8',
    default_load: 'Moderate-Heavy',
    default_rest_seconds: 150,
  },
  {
    name: 'Close-Grip Barbell Bench Press',
    primary_muscle_group: 'Triceps',
    secondary_muscle_groups: ['Chest'],
    movement_pattern: 'Horizontal Push',
    equipment: 'Barbell/Bench',
    category: 'Strength',
    default_sets: 3,
    default_reps: '6–10',
    default_load: 'Moderate',
    default_rest_seconds: 120,
  },
  {
    name: 'Incline Barbell Bench Press',
    primary_muscle_group: 'Upper Chest',
    secondary_muscle_groups: ['Shoulders', 'Triceps'],
    movement_pattern: 'Horizontal Push',
    equipment: 'Barbell/Bench',
    category: 'Strength',
    default_sets: 3,
    default_reps: '6–10',
    default_load: 'Moderate',
    default_rest_seconds: 120,
  },
  {
    name: 'Barbell Overhead Press',
    primary_muscle_group: 'Shoulders',
    secondary_muscle_groups: ['Triceps'],
    movement_pattern: 'Vertical Push',
    equipment: 'Barbell/Rack',
    category: 'Strength',
    default_sets: 3,
    default_reps: '5–8',
    default_load: 'Moderate-Heavy',
    default_rest_seconds: 150,
  },
  {
    name: 'Push Press',
    primary_muscle_group: 'Shoulders',
    secondary_muscle_groups: ['Triceps', 'Quads'],
    movement_pattern: 'Vertical Push',
    equipment: 'Barbell/Rack',
    category: 'Power',
    default_sets: 3,
    default_reps: '3–5',
    default_load: 'Heavy',
    default_rest_seconds: 150,
  },
  {
    name: 'Barbell Bent-Over Row',
    primary_muscle_group: 'Mid Back',
    secondary_muscle_groups: ['Lats', 'Biceps'],
    movement_pattern: 'Horizontal Pull',
    equipment: 'Barbell/Rack',
    category: 'Strength',
    default_sets: 3,
    default_reps: '6–10',
    default_load: 'Moderate-Heavy',
    default_rest_seconds: 120,
  },
  {
    name: 'Pendlay Row',
    primary_muscle_group: 'Mid Back',
    secondary_muscle_groups: ['Lats', 'Biceps'],
    movement_pattern: 'Horizontal Pull',
    equipment: 'Barbell/Rack',
    category: 'Strength',
    default_sets: 3,
    default_reps: '5–8',
    default_load: 'Heavy',
    default_rest_seconds: 150,
  },

  // Dumbbell chest & shoulders
  {
    name: 'Dumbbell Bench Press',
    primary_muscle_group: 'Chest',
    secondary_muscle_groups: ['Triceps', 'Shoulders'],
    movement_pattern: 'Horizontal Push',
    equipment: 'Dumbbells/Bench',
    category: 'Hypertrophy',
    default_sets: 3,
    default_reps: '8–12',
    default_load: 'Moderate',
    default_rest_seconds: 90,
  },
  {
    name: 'Incline Dumbbell Bench Press',
    primary_muscle_group: 'Upper Chest',
    secondary_muscle_groups: ['Shoulders', 'Triceps'],
    movement_pattern: 'Horizontal Push',
    equipment: 'Dumbbells/Bench',
    category: 'Hypertrophy',
    default_sets: 3,
    default_reps: '8–12',
    default_load: 'Moderate',
    default_rest_seconds: 90,
  },
  {
    name: 'Dumbbell Flyes',
    primary_muscle_group: 'Chest',
    movement_pattern: 'Horizontal Push',
    equipment: 'Dumbbells/Bench',
    category: 'Accessory',
    default_sets: 3,
    default_reps: '10–15',
    default_load: 'Light-Moderate',
    default_rest_seconds: 60,
  },
  {
    name: 'Dumbbell Shoulder Press',
    primary_muscle_group: 'Shoulders',
    secondary_muscle_groups: ['Triceps'],
    movement_pattern: 'Vertical Push',
    equipment: 'Dumbbells/Bench',
    category: 'Hypertrophy',
    default_sets: 3,
    default_reps: '8–12',
    default_load: 'Moderate',
    default_rest_seconds: 90,
  },
  {
    name: 'Seated Dumbbell Shoulder Press',
    primary_muscle_group: 'Shoulders',
    secondary_muscle_groups: ['Triceps'],
    movement_pattern: 'Vertical Push',
    equipment: 'Dumbbells/Bench',
    category: 'Hypertrophy',
    default_sets: 3,
    default_reps: '8–12',
    default_load: 'Moderate',
    default_rest_seconds: 90,
  },
  {
    name: 'Dumbbell Lateral Raise',
    primary_muscle_group: 'Shoulders',
    movement_pattern: 'Accessory',
    equipment: 'Dumbbells',
    category: 'Accessory',
    default_sets: 3,
    default_reps: '12–15',
    default_load: 'Light',
    default_rest_seconds: 60,
  },
  {
    name: 'Dumbbell Rear Delt Fly',
    primary_muscle_group: 'Rear Delts',
    secondary_muscle_groups: ['Upper Back'],
    movement_pattern: 'Accessory',
    equipment: 'Dumbbells',
    category: 'Accessory',
    default_sets: 3,
    default_reps: '12–15',
    default_load: 'Light',
    default_rest_seconds: 60,
  },

  // Dumbbell back & arms
  {
    name: 'One-Arm Dumbbell Row',
    primary_muscle_group: 'Lats',
    secondary_muscle_groups: ['Mid Back', 'Biceps'],
    movement_pattern: 'Horizontal Pull',
    equipment: 'Dumbbells/Bench',
    category: 'Hypertrophy',
    default_sets: 3,
    default_reps: '8–12',
    default_load: 'Moderate',
    default_rest_seconds: 90,
  },
  {
    name: 'Dumbbell Chest-Supported Row',
    primary_muscle_group: 'Mid Back',
    secondary_muscle_groups: ['Lats', 'Biceps'],
    movement_pattern: 'Horizontal Pull',
    equipment: 'Dumbbells/Bench',
    category: 'Hypertrophy',
    default_sets: 3,
    default_reps: '8–12',
    default_load: 'Moderate',
    default_rest_seconds: 90,
  },
  {
    name: 'Dumbbell Hammer Curl',
    primary_muscle_group: 'Biceps',
    movement_pattern: 'Accessory',
    equipment: 'Dumbbells',
    category: 'Accessory',
    default_sets: 3,
    default_reps: '8–12',
    default_load: 'Moderate',
    default_rest_seconds: 60,
  },
  {
    name: 'Dumbbell Biceps Curl',
    primary_muscle_group: 'Biceps',
    movement_pattern: 'Accessory',
    equipment: 'Dumbbells',
    category: 'Accessory',
    default_sets: 3,
    default_reps: '10–15',
    default_load: 'Light-Moderate',
    default_rest_seconds: 60,
  },
  {
    name: 'Incline Dumbbell Curl',
    primary_muscle_group: 'Biceps',
    movement_pattern: 'Accessory',
    equipment: 'Dumbbells/Bench',
    category: 'Accessory',
    default_sets: 3,
    default_reps: '8–12',
    default_load: 'Moderate',
    default_rest_seconds: 60,
  },
  {
    name: 'Dumbbell Overhead Triceps Extension',
    primary_muscle_group: 'Triceps',
    movement_pattern: 'Accessory',
    equipment: 'Dumbbells',
    category: 'Accessory',
    default_sets: 3,
    default_reps: '10–15',
    default_load: 'Light-Moderate',
    default_rest_seconds: 60,
  },

  // Dumbbell lower body
  {
    name: 'Goblet Squat',
    primary_muscle_group: 'Quads',
    secondary_muscle_groups: ['Glutes'],
    movement_pattern: 'Squat',
    equipment: 'Dumbbells',
    category: 'Hypertrophy',
    default_sets: 3,
    default_reps: '8–12',
    default_load: 'Moderate',
    default_rest_seconds: 90,
  },
  {
    name: 'Dumbbell Romanian Deadlift',
    primary_muscle_group: 'Hamstrings',
    secondary_muscle_groups: ['Glutes'],
    movement_pattern: 'Hinge',
    equipment: 'Dumbbells',
    category: 'Hypertrophy',
    default_sets: 3,
    default_reps: '8–12',
    default_load: 'Moderate',
    default_rest_seconds: 90,
  },
  {
    name: 'Dumbbell Walking Lunge',
    primary_muscle_group: 'Quads',
    secondary_muscle_groups: ['Glutes', 'Hamstrings'],
    movement_pattern: 'Lunge',
    equipment: 'Dumbbells',
    category: 'Hypertrophy',
    default_sets: 3,
    default_reps: '8–12/leg',
    default_load: 'Moderate',
    default_rest_seconds: 90,
  },
  {
    name: 'Bulgarian Split Squat (Dumbbell)',
    primary_muscle_group: 'Quads',
    secondary_muscle_groups: ['Glutes'],
    movement_pattern: 'Lunge',
    equipment: 'Dumbbells/Bench',
    category: 'Hypertrophy',
    default_sets: 3,
    default_reps: '8–12/leg',
    default_load: 'Moderate',
    default_rest_seconds: 90,
  },
  {
    name: 'Dumbbell Step-Up',
    primary_muscle_group: 'Quads',
    secondary_muscle_groups: ['Glutes'],
    movement_pattern: 'Lunge',
    equipment: 'Dumbbells/Box',
    category: 'Hypertrophy',
    default_sets: 3,
    default_reps: '8–12/leg',
    default_load: 'Moderate',
    default_rest_seconds: 90,
  },

  // Nordic / posterior chain
  {
    name: 'Nordic Hamstring Curl',
    primary_muscle_group: 'Hamstrings',
    movement_pattern: 'Accessory',
    equipment: 'Nordic Curler',
    category: 'Strength/Accessory',
    default_sets: 3,
    default_reps: '4–8',
    default_load: 'Bodyweight',
    default_rest_seconds: 120,
  },
  {
    name: 'Assisted Nordic Hamstring Curl (Bands)',
    primary_muscle_group: 'Hamstrings',
    movement_pattern: 'Accessory',
    equipment: 'Nordic Curler/Bands',
    category: 'Accessory',
    default_sets: 3,
    default_reps: '6–10',
    default_load: 'Bodyweight + Assistance',
    default_rest_seconds: 90,
  },

  // Box & plyometrics
  {
    name: 'Box Jump',
    primary_muscle_group: 'Quads',
    secondary_muscle_groups: ['Glutes', 'Calves'],
    movement_pattern: 'Plyometric',
    equipment: 'Box',
    category: 'Power',
    default_sets: 3,
    default_reps: '3–5',
    default_load: 'Bodyweight',
    default_rest_seconds: 90,
  },
  {
    name: 'Lateral Box Jump',
    primary_muscle_group: 'Quads',
    secondary_muscle_groups: ['Glutes'],
    movement_pattern: 'Plyometric',
    equipment: 'Box',
    category: 'Power',
    default_sets: 3,
    default_reps: '3–5',
    default_load: 'Bodyweight',
    default_rest_seconds: 90,
  },
  {
    name: 'Box Step-Down',
    primary_muscle_group: 'Quads',
    movement_pattern: 'Accessory',
    equipment: 'Box',
    category: 'Accessory',
    default_sets: 2,
    default_reps: '10–12/leg',
    default_load: 'Bodyweight',
    default_rest_seconds: 60,
  },

  // Sled work
  {
    name: 'Sled Push (Heavy)',
    primary_muscle_group: 'Quads',
    secondary_muscle_groups: ['Glutes'],
    movement_pattern: 'Conditioning',
    equipment: 'Sled Pusher',
    category: 'Conditioning',
    default_sets: 4,
    default_reps: '20–30m',
    default_load: 'Heavy',
    default_rest_seconds: 90,
  },
  {
    name: 'Sled Push (Speed)',
    primary_muscle_group: 'Quads',
    movement_pattern: 'Conditioning',
    equipment: 'Sled Pusher',
    category: 'Conditioning',
    default_sets: 4,
    default_reps: '15–20m',
    default_load: 'Moderate',
    default_rest_seconds: 60,
  },
  {
    name: 'Backward Sled Drag',
    primary_muscle_group: 'Quads',
    movement_pattern: 'Conditioning',
    equipment: 'Sled Pusher',
    category: 'Conditioning',
    default_sets: 3,
    default_reps: '20–30m',
    default_load: 'Moderate',
    default_rest_seconds: 60,
  },

  // Band work
  {
    name: 'Band Pull-Apart',
    primary_muscle_group: 'Rear Delts',
    secondary_muscle_groups: ['Upper Back'],
    movement_pattern: 'Accessory',
    equipment: 'Bands',
    category: 'Warmup/Accessory',
    default_sets: 2,
    default_reps: '15–20',
    default_load: 'Light',
    default_rest_seconds: 30,
  },
  {
    name: 'Band Face Pull',
    primary_muscle_group: 'Rear Delts',
    secondary_muscle_groups: ['Upper Back'],
    movement_pattern: 'Accessory',
    equipment: 'Bands',
    category: 'Warmup/Accessory',
    default_sets: 3,
    default_reps: '12–15',
    default_load: 'Light',
    default_rest_seconds: 45,
  },
  {
    name: 'Band Assisted Pull-Up',
    primary_muscle_group: 'Lats',
    secondary_muscle_groups: ['Biceps'],
    movement_pattern: 'Vertical Pull',
    equipment: 'Bands',
    category: 'Strength/Accessory',
    default_sets: 3,
    default_reps: '6–10',
    default_load: 'Bodyweight + Assistance',
    default_rest_seconds: 90,
  },
  {
    name: 'Band Triceps Pushdown',
    primary_muscle_group: 'Triceps',
    movement_pattern: 'Accessory',
    equipment: 'Bands',
    category: 'Accessory',
    default_sets: 3,
    default_reps: '12–15',
    default_load: 'Light',
    default_rest_seconds: 45,
  },
  {
    name: 'Band Biceps Curl',
    primary_muscle_group: 'Biceps',
    movement_pattern: 'Accessory',
    equipment: 'Bands',
    category: 'Accessory',
    default_sets: 3,
    default_reps: '12–15',
    default_load: 'Light',
    default_rest_seconds: 45,
  },

  // BikeErg
  {
    name: 'BikeErg Steady State',
    primary_muscle_group: 'Cardio',
    movement_pattern: 'Conditioning',
    equipment: 'BikeErg',
    category: 'Conditioning',
    default_sets: 1,
    default_reps: '10–30 min',
    default_load: 'Easy-Moderate',
  },
  {
    name: 'BikeErg Intervals (1:1)',
    primary_muscle_group: 'Cardio',
    movement_pattern: 'Conditioning',
    equipment: 'BikeErg',
    category: 'Conditioning',
    default_sets: 8,
    default_reps: '30s hard / 30s easy',
    default_load: 'Hard',
    default_rest_seconds: 30,
  },
  {
    name: 'BikeErg Sprint Intervals',
    primary_muscle_group: 'Cardio',
    movement_pattern: 'Conditioning',
    equipment: 'BikeErg',
    category: 'Conditioning',
    default_sets: 10,
    default_reps: '10s all-out / 50s easy',
    default_load: 'Max Effort',
  },

  // SkiErg
  {
    name: 'SkiErg Steady State',
    primary_muscle_group: 'Cardio',
    secondary_muscle_groups: ['Lats', 'Shoulders'],
    movement_pattern: 'Conditioning',
    equipment: 'SkiErg',
    category: 'Conditioning',
    default_sets: 1,
    default_reps: '8–20 min',
    default_load: 'Easy-Moderate',
  },
  {
    name: 'SkiErg 500m Intervals',
    primary_muscle_group: 'Cardio',
    movement_pattern: 'Conditioning',
    equipment: 'SkiErg',
    category: 'Conditioning',
    default_sets: 4,
    default_reps: '500m hard / 2–3 min rest',
    default_load: 'Hard',
  },
  {
    name: 'SkiErg Sprint Intervals',
    primary_muscle_group: 'Cardio',
    movement_pattern: 'Conditioning',
    equipment: 'SkiErg',
    category: 'Conditioning',
    default_sets: 8,
    default_reps: '20s hard / 40s easy',
    default_load: 'Hard',
  },

  // Treadmill
  {
    name: 'Treadmill Incline Walk',
    primary_muscle_group: 'Cardio',
    movement_pattern: 'Conditioning',
    equipment: 'Treadmill',
    category: 'Conditioning',
    default_sets: 1,
    default_reps: '10–30 min',
    default_load: 'Easy-Moderate',
  },
  {
    name: 'Treadmill Jog',
    primary_muscle_group: 'Cardio',
    movement_pattern: 'Conditioning',
    equipment: 'Treadmill',
    category: 'Conditioning',
    default_sets: 1,
    default_reps: '10–25 min',
    default_load: 'Moderate',
  },
  {
    name: 'Treadmill Sprint Intervals',
    primary_muscle_group: 'Cardio',
    movement_pattern: 'Conditioning',
    equipment: 'Treadmill',
    category: 'Conditioning',
    default_sets: 8,
    default_reps: '15–30s sprint / 60–90s walk',
    default_load: 'Hard',
  },

  // Bodyweight / bench-based
  {
    name: 'Push-Up',
    primary_muscle_group: 'Chest',
    secondary_muscle_groups: ['Triceps', 'Shoulders'],
    movement_pattern: 'Horizontal Push',
    equipment: 'Bodyweight',
    category: 'Strength/Accessory',
    default_sets: 3,
    default_reps: 'AMRAP or 8–15',
    default_load: 'Bodyweight',
    default_rest_seconds: 60,
  },
  {
    name: 'Incline Push-Up (Bench)',
    primary_muscle_group: 'Chest',
    secondary_muscle_groups: ['Triceps', 'Shoulders'],
    movement_pattern: 'Horizontal Push',
    equipment: 'Bench',
    category: 'Accessory',
    default_sets: 3,
    default_reps: '10–15',
    default_load: 'Bodyweight',
    default_rest_seconds: 60,
  },
  {
    name: 'Bench Dips',
    primary_muscle_group: 'Triceps',
    secondary_muscle_groups: ['Chest'],
    movement_pattern: 'Accessory',
    equipment: 'Bench',
    category: 'Accessory',
    default_sets: 3,
    default_reps: '8–15',
    default_load: 'Bodyweight',
    default_rest_seconds: 60,
  },
  {
    name: 'Hip Thrust (Bench + Barbell)',
    primary_muscle_group: 'Glutes',
    secondary_muscle_groups: ['Hamstrings'],
    movement_pattern: 'Hip Extension',
    equipment: 'Barbell/Bench',
    category: 'Hypertrophy',
    default_sets: 3,
    default_reps: '8–12',
    default_load: 'Moderate-Heavy',
    default_rest_seconds: 120,
  },
  {
    name: 'Single-Leg Hip Thrust (Bench)',
    primary_muscle_group: 'Glutes',
    movement_pattern: 'Hip Extension',
    equipment: 'Bench',
    category: 'Accessory',
    default_sets: 3,
    default_reps: '10–15/leg',
    default_load: 'Bodyweight',
    default_rest_seconds: 90,
  },

  // Core
  {
    name: 'Plank',
    primary_muscle_group: 'Core',
    movement_pattern: 'Anti-Extension',
    equipment: 'Bodyweight',
    category: 'Core',
    default_sets: 3,
    default_reps: '20–45s',
    default_load: 'Bodyweight',
    default_rest_seconds: 45,
  },
  {
    name: 'Side Plank',
    primary_muscle_group: 'Obliques',
    movement_pattern: 'Anti-Lateral Flexion',
    equipment: 'Bodyweight',
    category: 'Core',
    default_sets: 3,
    default_reps: '20–40s/side',
    default_load: 'Bodyweight',
    default_rest_seconds: 45,
  },
  {
    name: 'Dead Bug',
    primary_muscle_group: 'Core',
    movement_pattern: 'Core Control',
    equipment: 'Bodyweight',
    category: 'Core/Warmup',
    default_sets: 2,
    default_reps: '8–12/side',
    default_load: 'Bodyweight',
    default_rest_seconds: 30,
  },
  {
    name: 'Hollow Body Hold',
    primary_muscle_group: 'Core',
    movement_pattern: 'Anti-Extension',
    equipment: 'Bodyweight',
    category: 'Core',
    default_sets: 3,
    default_reps: '15–30s',
    default_load: 'Bodyweight',
    default_rest_seconds: 45,
  },
];

async function seedExerciseLibrary() {
  console.log('🌱 Seeding exercise library...\n');

  const client = await pool.connect();

  try {
    for (const ex of EXERCISES) {
      // Check if exercise already exists (case-insensitive by name)
      const existing = await client.query<{
        id: number;
      }>(
        'SELECT id FROM exercise_library_exercises WHERE LOWER(name) = LOWER($1)',
        [ex.name]
      );

      if (existing.rows.length > 0) {
        console.log(`⚠️  Exercise "${ex.name}" already exists, skipping...`);
        continue;
      }

      await client.query(
        `INSERT INTO exercise_library_exercises (
          name,
          primary_muscle_group,
          secondary_muscle_groups,
          movement_pattern,
          equipment,
          category,
          default_sets,
          default_reps,
          default_load,
          default_rest_seconds,
          default_tempo,
          notes,
          status
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, 'active')`,
        [
          ex.name,
          ex.primary_muscle_group || null,
          ex.secondary_muscle_groups || null,
          ex.movement_pattern || null,
          ex.equipment || null,
          ex.category || null,
          ex.default_sets ?? null,
          ex.default_reps || null,
          ex.default_load || null,
          ex.default_rest_seconds ?? null,
          ex.default_tempo || null,
          ex.notes || null,
        ]
      );

      console.log(`✅ Inserted exercise: ${ex.name}`);
    }

    console.log('\n✨ Exercise library seeding complete!');
  } catch (error) {
    console.error('❌ Error seeding exercise library:', error);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
    process.exit(0);
  }
}

seedExerciseLibrary();

