import type { Section } from './types';

export const QUESTIONNAIRE_SECTIONS: Section[] = [
  {
    title: 'Section 1 – Starting Point',
    description: "Understanding where you're starting from",
    questions: [
      {
        type: 'slider',
        fieldName: 'section1_energy_level',
        label: 'How healthy and energetic do you feel on a typical day?',
        minLabel: '1 - Not at all',
        maxLabel: '10 - Extremely',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
      {
        type: 'slider',
        fieldName: 'section1_exercise_consistency',
        label: 'How consistent have you been with exercise over the past 3 months?',
        minLabel: '1 - Not consistent',
        maxLabel: '10 - Very consistent',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
      {
        type: 'slider',
        fieldName: 'section1_strength_confidence',
        label: 'How confident do you feel performing strength-based movements?',
        minLabel: '1 - Not confident',
        maxLabel: '10 - Very confident',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
      {
        type: 'textarea',
        fieldName: 'section1_limiting_factors',
        label: "Briefly describe what's been holding you back or limiting progress.",
        placeholder: "Share what's been challenging...",
        rows: 3,
      },
    ],
  },
  {
    title: 'Section 2 – Motivation & Mindset',
    description: 'What drives you and keeps you going',
    questions: [
      {
        type: 'slider',
        fieldName: 'section2_motivation',
        label: 'How motivated are you to make a real change right now?',
        minLabel: '1 - Not motivated',
        maxLabel: '10 - Extremely motivated',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
      {
        type: 'slider',
        fieldName: 'section2_discipline',
        label: 'How disciplined do you tend to be once a plan is in place?',
        minLabel: '1 - Not disciplined',
        maxLabel: '10 - Very disciplined',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
      {
        type: 'slider',
        fieldName: 'section2_support_level',
        label: 'How supported do you feel in your current environment (friends/family/routine)?',
        minLabel: '1 - Not supported',
        maxLabel: '10 - Very supported',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
      {
        type: 'textarea',
        fieldName: 'section2_what_keeps_going',
        label: 'What typically keeps you going when training gets challenging?',
        placeholder: 'Share what motivates you...',
        rows: 3,
      },
    ],
  },
  {
    title: 'Section 3 – Body & Movement',
    description: 'Understanding your physical capabilities',
    questions: [
      {
        type: 'slider',
        fieldName: 'section3_pain_limitations',
        label: 'How limited do you feel by pain, injury, or past issues?',
        minLabel: '1 - Not limited',
        maxLabel: '10 - Very limited',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
      {
        type: 'slider',
        fieldName: 'section3_mobility_confidence',
        label: 'How confident are you in your mobility and range of motion?',
        minLabel: '1 - Not confident',
        maxLabel: '10 - Very confident',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
      {
        type: 'slider',
        fieldName: 'section3_strength_comparison',
        label: 'How strong do you feel compared to your ideal self?',
        minLabel: '1 - Not strong',
        maxLabel: '10 - Very strong',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
    ],
  },
  {
    title: 'Section 4 – Nutrition & Recovery',
    description: 'Assessing your recovery and fueling habits',
    questions: [
      {
        type: 'slider',
        fieldName: 'section4_nutrition_alignment',
        label: 'How aligned do you feel your nutrition habits are with your goals?',
        minLabel: '1 - Not aligned',
        maxLabel: '10 - Very aligned',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
      {
        type: 'slider',
        fieldName: 'section4_meal_consistency',
        label: 'How consistent is your meal pattern and portion awareness?',
        minLabel: '1 - Not consistent',
        maxLabel: '10 - Very consistent',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
      {
        type: 'slider',
        fieldName: 'section4_sleep_quality',
        label: 'How well do you sleep and recover?',
        minLabel: '1 - Poor',
        maxLabel: '10 - Excellent',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
      {
        type: 'slider',
        fieldName: 'section4_stress_level',
        label: 'How much daily stress do you carry right now?',
        minLabel: '1 - No stress',
        maxLabel: '10 - Extreme stress',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
    ],
  },
  {
    title: 'Section 5 – Identity & Self-Perception',
    description: 'Understanding your relationship with your body and goals',
    questions: [
      {
        type: 'slider',
        fieldName: 'section5_body_connection',
        label: 'How connected do you feel to your body right now?',
        minLabel: '1 - Not connected',
        maxLabel: '10 - Very connected',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
      {
        type: 'slider',
        fieldName: 'section5_appearance_satisfaction',
        label: 'How satisfied are you with your current physical appearance?',
        minLabel: '1 - Not satisfied',
        maxLabel: '10 - Very satisfied',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
      {
        type: 'slider',
        fieldName: 'section5_motivation_driver',
        label: 'How much of your motivation is driven by appearance vs. performance/longevity?',
        minLabel: '1 - Performance/Longevity',
        maxLabel: '10 - Appearance',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
      {
        type: 'slider',
        fieldName: 'section5_sustainability_confidence',
        label: "How confident are you that you'll sustain results once you achieve them?",
        minLabel: '1 - Not confident',
        maxLabel: '10 - Very confident',
        min: 1,
        max: 10,
        defaultValue: 5,
      },
      {
        type: 'textarea',
        fieldName: 'section5_success_vision',
        label: 'Describe briefly what "success" would look and feel like six months from now.',
        placeholder: 'Paint a picture of your success...',
        rows: 4,
      },
    ],
  },
];

